name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. التحقق من الكود
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. إعداد Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. بناء صورة Docker
      - name: Build Docker image
        run: |
          docker build -t my-react-vite-app .

      # 4. تشغيل الحاوية (container)
      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 my-react-vite-app

      # 5. تشغيل الاختبارات داخل الحاوية (اختياري)
      - name: Run Tests in Docker container
        run: |
          if [ $(docker ps -q -f name=my-react-vite-app) ]; then
            docker exec my-react-vite-app npm test
          else
            echo "Container not running. Skipping tests."
          fi

      # 6. إيقاف الحاوية بعد انتهاء الاختبارات
      - name: Stop and remove Docker container
        run: |
          if [ $(docker ps -q -f name=my-react-vite-app) ]; then
            docker stop my-react-vite-app
            docker rm my-react-vite-app
          else
            echo "Container is not running."
          fi

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      # نشر التطبيق
      - name: Checkout Repository (Deploy)
        uses: actions/checkout@v3

      # نشر التطبيق (إذا كان لديك خطوة نشر إلى منصة)
      - name: Deploy to Production
        run: |
          echo "Starting deployment to production..."
          # ضع هنا سكربت النشر الفعلي
          echo "Deployment Complete!"
        env:
          DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
